# Start development with installing all dependencies
# bundle install

# Then run the website locally (go to localhost:4000 in your browser)
# bundle exec jekyll serve --config _config.yml,_config_dev.yml

# If port busy, check whuch process (PID) is using it and kill it
# sudo lsof -i tcp:4000
# kill -9 PID

port: 4000
url: 'http://localhost:4000'
urlimg: 'http://localhost:4000/images/'

# # See › https://github.com/jekyll/jekyll-gist#disabling-noscript-support
# gist:
#   noscript: false

sass:
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: :expanded
  line_numbers: true
  # trace_selectors: true
  # debug_info: true
  # FUTURE https://github.com/jekyll/jekyll-sass-converter/issues/12
  # sourcemap: true # Produces an error

# # Disable when not in production
# google_analytics_tracking_id: false
